services:
  - type: web
    name: corteus-fastapi
    env: python
    pythonVersion: "3.11.4"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: RENDER
        value: "true"
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: "ALTERAR_ESTA_SENHA_123"
