[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#ff4b4b"
backgroundColor="#18191a"
secondaryBackgroundColor="#23272f"
textColor="#ffffff"
font="sans serif"